openapi: 3.0.2
info:
  title: test plain result mapping
  version: 1.0.0

paths:
  /foo:
    get:
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: plain result

  /bar:
    get:
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: plain result
