openapi: 3.0.2
info:
  title: test enum parameters
  version: 1.0.0

paths:

  /endpoint:
    get:
      tags:
        - enum
      parameters:
        - name: foo
          description: enum parameter
          in: query
          required: true
          schema:
            type: string
            enum:
              - foo
              - foo-2
              - foo-foo
        - name: bar
          description: enum parameter
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Bar'
      responses:
        '204':
          description: empty

components:
  schemas:

    Bar:
      type: string
      enum:
        - bar
        - bar-2
        - bar-bar
