openapi: 3.0.2
info:
  title: test basic data type responses
  version: 1.0.0

paths:
  /string:
    get:
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: none

  /integer:
    get:
      responses:
        '200':
          content:
            application/vnd.integer:
              schema:
                type: integer
                format: int32
          description: none

  /long:
    get:
      responses:
        '200':
          content:
            application/vnd.long:
              schema:
                type: integer
                format: int64
          description: none

  /float:
    get:
      responses:
        '200':
          content:
            application/vnd.float:
              schema:
                type: number
                format: float
          description: none

  /double:
    get:
      responses:
        '200':
          content:
            application/vnd.double:
              schema:
                type: number
                format: double
          description: none

  /boolean:
    get:
      responses:
        '200':
          content:
            application/vnd.boolean:
              schema:
                type: boolean
          description: none

  /array-string:
    get:
      responses:
        '200':
          content:
            application/vnd.array:
              schema:
                type: array
                items:
                  type: string
          description: none

#  /array-collection:
#    get:
#      responses:
#        '200':
#          content:
#            application/vnd.collection:
#              schema:
#                type: array
#                items:
#                  type: string
#          description: none
