openapi: 3.0.2
info:
  title: test complex parameters
  version: 1.0.0

paths:

  /endpoint-object:
    get:
      description: <
        should be mapped to a `Props` pojo without `@RequestParam` annotation

          /endpoint-object?prop1=foo&prop2=bar

      parameters:
        - name: props
          description: query parameter object
          in: query
          schema:
            $ref: '#/components/schemas/Props'
      responses:
        '204':
          description: empty

  /endpoint-map:
    get:
      description: <
        should be mapped to a `Map` (from mapping) with `@RequestParam` annotation
      parameters:
        - name: props
          description: query parameter object
          in: query
          schema:
            $ref: '#/components/schemas/Props'
      responses:
        '204':
          description: empty

  /endpoint-multi-map:
    get:
      parameters:
        - name: props
          description: <
            should be mapped to a `MultiValueMap` (from mapping) with `@RequestParam` annotation
          in: query
          schema:
            $ref: '#/components/schemas/Props'
      responses:
        '204':
          description: empty

components:

  schemas:

    Props:
      type: object
      properties:
        prop1:
          type: string
        prop2:
          type: string
