openapi: 3.0.2
info:
  title: test complex parameters
  version: 1.0.0

paths:

  /endpoint-object:
    get:
      description: <
        should be mapped to a `Props` pojo without `@RequestParam` annotation
      parameters:
        - name: props
          description: query parameter object
          in: query
          required: false
          explode: true
          schema:
            $ref: '#/components/schemas/Props'
      responses:
        '204':
          description: empty

components:

  schemas:

    Props:
      type: object
      properties:
        prop1:
          type: string
        prop2:
          type: string
