openapi: 3.0.2
info:
  title: test $ref into other file
  version: 1.0.0

paths:

  /book:
    get:
      responses:
        '200':
          description: none
          content:
            application/json:
                schema:
                  $ref: 'book.yaml#/Book'
