openapi: 3.0.2
info:
  title: test simple parameters
  version: 1.0.0

paths:
  /endpoint:
    get:
      tags:
        - endpoint
      parameters:
        - name: foo
          description: query, required, string
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: empty

  /endpoint-optional:
    get:
      tags:
        - endpoint
      parameters:
        - name: foo
          description: query, not required, string
          in: query
          required: false
          schema:
            type: string
            default: bar
      responses:
        '204':
          description: empty
