openapi: 3.0.2
info:
  title: test complex data type responses
  version: 1.0.0

paths:
  /book-inline:
    get:
      responses:
        '200':
          description: none
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    isbn:
                      type: string
                    title:
                      type: string

  /book:
    get:
      responses:
        '200':
          description: none
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Book'

  /book-nested:
    get:
      responses:
        '200':
          description: none
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/BookNested'

components:
  schemas:
    Book:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string

    BookNested:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        author:
          $ref: '#/components/schemas/Author'

    Author:
      type: object
      properties:
        name:
          type: string
